teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
  - name: openreagent-maintainers
    maintainers:
      - superkimchi
    members:
      - jisupark
repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
  - name: openreagent
    teams:
      lf-staff: maintain
      openreagent-maintainers: maintain
    visibility: public
